spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://database-1.cd5vpjxhrb6d.ap-northeast-2.rds.amazonaws.com:3306/appler?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: administrator
      password: ritkfygh12

  thymeleaf:
    cache : false

   #실제 운영시 true
#mybatis:
 # type-aliases-package: com.ys.Appler.dto
  #mapper-locations: classpath:mybatis/mapper/*.xml

